name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World!"
            echo "Is everything OK?"
            sleep 1
      - name: Print goodbye
        run: |
            echo "That's great!"
            echo "Goodbye!"
